### ISSUE TITLE
ResLibCal - ResLibCal_fig and scripting

### ISSUE THREAD

**Issue by substance33** [McStasMcXtrace/iFit#1]
Hi Emmanuel,

I'm currently running ResLibCal through a script, unfortunately it calls the function thousands of times. I have profiled ResLibCal and found that the 'compute' switch is taking far longer than expected. When computing, the function ResLibCal_fig takes up a large amount of time due to the _findall_ command. I propose that a separate switch 'script' is incorporated; 

_case {'script'}
      % if no interface exists, load the last saved configuration before computing
      out = ResLibCal_Compute(out);_

Or reworking 'update' switch, moving _fig = ResLibCal_fig;_ on line 430 to after the ~silent_mode if statement on line 434.

I have modified my local copy using the 'script' workaround and found it to be much faster.

Many Thanks :-)

Simon

**Comment by farhi** [comment]
Hello Simon,

thanks for using ResLibCal. Your suggestion to move the call to ResLibCal_fig after the 'silent_mode' test is certainly welcome. You can then run very fast by issuing ResLibCal('silent','update').
I have also commented the same call in the 'compute' action which is not used.

In principle, the ResLibCal_fig private function stores the handles to the objects, when they exist, so that further calls are much faster. This slow behaviour was 'introduced' by Matlab >= 2014b. It was not an issue before.

Thanks, Emmanuel.
